# Generated by Django 2.2.5 on 2019-09-22 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_SBP_per_upload', models.IntegerField(blank=True, null=True)),
                ('average_pulse_rate_per_upload', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_status', models.CharField(blank=True, max_length=50, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.ApplicationClient')),
            ],
        ),
        migrations.CreateModel(
            name='ClientDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_mood', models.CharField(blank=True, max_length=50, null=True)),
                ('event_description', models.CharField(blank=True, max_length=50, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressureInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic_blood_pressure', models.IntegerField(blank=True, null=True)),
                ('diastolic_blood_pressure', models.IntegerField(blank=True, null=True)),
                ('pulse_rate', models.IntegerField(blank=True, null=True)),
                ('upload_count', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('average_of_inputs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_account.BloodPressureData')),
            ],
        ),
        migrations.AddField(
            model_name='bloodpressuredata',
            name='diary_input',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_account.ClientDiary'),
        ),
    ]
