# Generated by Django 2.2.5 on 2019-09-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpressuredata',
            name='average_DBP_per_upload',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
