# Generated by Django 2.2.5 on 2019-09-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0002_bloodpressuredata_average_dbp_per_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressureinput',
            name='datetime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
