# Generated by Django 2.2.5 on 2019-09-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0003_auto_20190927_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressureinput',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
