# Generated by Django 2.2.5 on 2019-09-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_applicationclient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_app_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_app_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_app_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
