# Generated by Django 2.2.5 on 2019-09-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190923_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_app_client',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_app_staff',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_app_superuser',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
